<div class="col-lg-2 col-md-2">
    <ul>
        <li>Sample1</li>
        <li>Sample2</li>
        <li>Sample3</li>
    </ul>
</div>
<div class="col-lg-10 col-md-10">
    <div class="row-fluid">
        Breadcrumbs here
    </div>
    <!-- TODO: advertisement widget -->
    <div class="row">
        <div class="col-lg-6">
            <img src="<?=$this->basePath('assets/img/site/ads/sale-banner.jpg')?>" style="width: 100%;">
        </div>
        <div class="col-lg-6">
            <img src="<?=$this->basePath('assets/img/site/ads/free-delivery-banner.jpg')?>"  style="width: 100%;">
        </div>
  </div>
</div>