<div class="container bazaarfoo">
    <div class="row">
        <section class="bazaarfoos">
            <!-- video playback -->
            <div class="col-sm-12 col-md-3 foo1">
                <div class="clearfix">
                    <div class="pull-left">
                        <p class="text-uppercase"><strong>See how <br> it works</strong></p>
                    </div>
                    <img class="playvid" src="img/play.png" alt="Play Bazaar video sale"><br>
                    <a href="#"><img src="img/video.png" alt=""></a>
                </div>
            </div><!-- end -->

            <!-- stay connected -->
            <div class="col-sm-12 col-md-3 foo2">
                <p><strong>Stay Connected</strong></p>
                <div class="clearfix">
                    <div class="pull-left">
                        <ul class="soc">
                            <li><a class="soc-facebook" href="#"></a></li>
                            <li><a class="soc-twitter soc-icon-last" href="#"></a></li>
                        </ul>
                    </div>
                    <p class="text-nowrap">bazaarcorner</p><br>
                    <p class="text-nowrap">#bazaarcorner</p>
                </div>
            </div><!-- end -->

            <!-- get updates -->
            <div class="col-sm-12 col-md-3 foo3">
                <p><strong>Get updates direct to your <span class="text-uppercase">email</span></strong></p>
                <form method="POST" action="">
                    <div class="form-group">
                        <div class="input-group">
                            <em><input type="text" class="form-control" placeholder="Enter your email here..."></em>
                            <span class="input-group-btn">
                                <input type="submit" class="btn btn-default" value="Submit">
                            </span>
                        </div>
                    </div>
                </form><br><br>
                <p><strong>Types of payment</strong></p>
                <img src="img/payments.png" alt="Type of payments">
            </div><!-- end -->

            <!-- copyright links -->
            <div class="col-sm-12 col-md-3 foo4">
                <p><strong>2014 BazaarCorner.com <br> All rights reserved</strong></p>
                <ul class="list-unstyled">
                    <li><a href="#">About Us</a></li>
                    <li><a href="#">Get Help</a></li>
                    <li><a href="#">Returns and Shipping</a></li>
                    <li><a href="#">Privacy Policy</a></li>
                    <li><a href="#">Terms and Conditions</a></li>
                    <li><a href="#">Contact Us</a></li>
                </ul>
            </div><!-- end -->
        </section>
    </div>
</div>