<div class="col-lg-10">
    <section id="us">
        <h3>About Us</h3>
        <p>
            Bazaar Corner is an virtual market place where people and merchants 
            can share and sell products online. A platform where it connects 
            merchants, individual boutiques, brands and consumers with an 
            amazing taste on the coolest products.
        </p>
    </section>
    <section id="mission-vision">
        <h3>We love to connect merchants and consumers</h3>
        <p>
            Our main mission is to revolutionize they way people shop online, 
            unlocking individuals' potential in selling. Making it as the safest
            e-commerce in world and making it more socialize and easy to use.
        </p>
    </section>
    <section id="team">
        <h3>Our Team</h3>
        <p>
            Our team
        </p>
    </section>
</div>

<!-- Navigation -->
<div class="col-lg-2">
    <ul>
        <li><a href="#us">About Us</li>
        <li><a href="#mission-vision">Mission and Vission</a></li>
        <li><a href="#team">Our Team</a></li>
    </ul>
</div>