<div class="col-lg-9 text-justify">
    <section id="registration">
        <h3>Membership</h3>
        <p>
            Donec vitae felis vel diam rutrum placerat eu et ipsum. Donec 
            ultrices urna at neque sodales pulvinar. Aliquam ut nulla ligula. 
            Sed id lacus sed orci pharetra mollis sed vestibulum nisi. Interdum 
            et malesuada fames ac ante ipsum primis in faucibus. Suspendisse 
            potenti. Etiam tempor aliquet tortor, quis lacinia elit sollicitudin
            non.
        </p>
        <p>
            Ut vehicula placerat posuere. Nam aliquet lorem quis erat congue
            sagittis. Ut luctus, velit at maximus mollis, sem magna efficitur
            urna, id finibus nulla elit ac erat. Aliquam non luctus velit. Nulla
            laoreet sit amet metus ullamcorper ultrices. Proin vitae quam 
            pretium, volutpat dui nec, aliquet nisl. In sollicitudin metus
            lacus. Pellentesque nec nulla a risus dictum sagittis. Sed finibus 
            lorem a ipsum imperdiet, ac tempor libero finibus. Nulla pharetra
            nec massa a iaculis.
        </p>
        <p>
            Nam ac ante non turpis fermentum bibendum. Quisque congue ac diam
            volutpat vulputate. In dapibus, neque sed lacinia sollicitudin,
            massa lacus congue nibh, ac ullamcorper lectus quam quis justo.
            Vivamus ac varius magna. Sed porttitor ipsum sed libero porta mollis
            sed nec justo. Etiam quis porttitor dui. Sed et dui in arcu mollis
            pellentesque. In hac habitasse platea dictumst. Vestibulum vehicula
            bibendum velit eget rhoncus. Class aptent taciti sociosqu ad litora
            torquent per conubia nostra, per inceptos himenaeos. Donec 
            ullamcorper turpis imperdiet interdum viverra. Proin sed quam in
            turpis sodales tempus. Aliquam erat volutpat.
        </p>
    </section>
    <section id="payments">
        <h3>Payment Methods</h3>
        <p>
            Sed maximus, erat a rutrum faucibus, lacus mauris condimentum eros,
            a consequat sem risus ac quam. Maecenas gravida fringilla erat eu
            cursus. Etiam commodo feugiat tincidunt. Pellentesque vehicula
            vulputate suscipit. Nam erat lectus, egestas eu sapien at, feugiat
            varius est. Nulla mattis scelerisque magna vitae cursus. Nunc
            consequat imperdiet felis, sit amet luctus risus lobortis ornare.
            Aenean quis nunc ex. Maecenas aliquet, arcu in cursus volutpat,
            massa turpis feugiat elit, ut interdum ipsum magna eu erat. Duis
            pretium, neque id bibendum tempus, metus tellus suscipit quam,
            quis blandit orci risus at augue. Etiam bibendum mi sed porta
            venenatis. Morbi id eros eget libero gravida tristique.
        </p>
    </section>
    <section id="orders">
        <h3>Tracking your Order</h3>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi
            sollicitudin volutpat pharetra. Fusce ac est sed magna molestie
            maximus. Aliquam scelerisque est ac augue tincidunt porta. Donec
            sed semper leo. Proin id purus vulputate, maximus velit ut, feugiat
            lectus. Aliquam molestie nisl id ante pellentesque facilisis. Morbi
            augue ipsum, tincidunt id maximus sed, suscipit eget dui. Proin
            ipsum ex, bibendum in turpis sit amet, pellentesque fermentum
            lectus. Nam scelerisque luctus urna, ac finibus elit sollicitudin
            ut.
        </p>
    </section>
</div>
<div class="col-lg-3">
    <h5>Frequently Asked Questions</h5>
    <ul>        
        <li><a href="#registration">Registration</a></li>
        <li><a href="#payments">Payment Methods</a></li>
        <li><a href="#orders">Tracking Orders</a></li>
    </ul>
</div>