<div class="col-lg-10 col-md-10 text-muted">
    <section id="company">
        <h3>Company Policy</h3>
        <p>
            Duis dictum metus ut est fringilla, ac ultricies nisl feugiat. Integer id tempus nibh. Pellentesque blandit viverra urna sed finibus. Aliquam sed erat at orci consequat euismod id vel dolor. Pellentesque at posuere turpis. Fusce euismod suscipit eros, sed euismod orci. Vivamus et diam suscipit, auctor est ac, suscipit odio. In congue, turpis ut lobortis placerat, libero risus pulvinar dui, et tempor nunc eros et lacus. Donec ante metus, tempus nec turpis sit amet, porttitor volutpat tortor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi molestie imperdiet consequat. Proin lacinia elit ante, nec commodo ipsum malesuada vitae. Praesent mollis gravida dui, a rutrum augue sodales eu. Pellentesque nec pretium dolor, a consequat est. Ut aliquet sed arcu suscipit lobortis. Integer efficitur aliquam urna, eget euismod quam mattis quis.
        </p>
        <p>
            Ut luctus tempus velit sed fermentum. Maecenas laoreet nunc eget erat dictum vulputate. Maecenas ultrices eros urna, vitae tempor quam gravida a. Vivamus enim justo, convallis vel mauris ac, facilisis ultricies tellus. Duis sit amet consectetur ipsum. Nulla vestibulum felis id dolor viverra, nec hendrerit odio fringilla. Sed iaculis dui felis, quis condimentum nisl ultricies id. Phasellus facilisis rhoncus egestas. Suspendisse tellus purus, auctor non turpis vitae, interdum congue ante. Nunc sollicitudin sem eros, ac auctor nisi feugiat eget. Cras molestie ac sapien suscipit lacinia. Nunc eget mollis lacus, non varius odio. Sed eu metus eu eros sollicitudin venenatis.
        </p>
    </section>
    <section id="membership">
        <h3>Members Privacy Policy</h3>
        <p>
            Your privacy is very important to us. Accordingly, we have developed this Policy in order for you to understand how we collect, use, communicate and disclose and make use of personal information. The following outlines our privacy policy.
        </p>
        <ul>
            <li>
                Before or at the time of collecting personal information, we will
                identify the purposes for which information is being collected.
            </li>
            <li>
                We will collect and use of personal information solely with the 
                objective of fulfilling those purposes specified by us and for other
                compatible purposes, unless we obtain the consent of the individual
                concerned or as required by law.		
            </li>
            <li>
                We will only retain personal information as long as necessary for
                the fulfillment of those purposes. 
            </li>
            <li>
                We will collect personal information by lawful and fair means and,
                where appropriate, with the knowledge or consent of the individual
                concerned. 
            </li>
            <li>
                Personal data should be relevant to the purposes for which it is to
                be used, and, to the extent necessary for those purposes, should be
                accurate, complete, and up-to-date. 
            </li>
            <li>
                We will protect personal information by reasonable security
                safeguards against loss or theft, as well as unauthorized access,
                disclosure, copying, use or modification.
            </li>
            <li>
                We will make readily available to customers information about our
                policies and practices relating to the management of personal
                information. 
            </li>
        </ul>
        <p>
            We are committed to conducting our business in accordance with these
            principles in order to ensure that the confidentiality of personal
            information is protected and maintained. 
        </p>
    </section>
    <section id="shipping">
        <h3>Shipping Policy</h3>
        <p>
            Seller/Merchant will received an order notification with the desired shipping method is included. And from that Seller/Merchant then must ship their products within 2 working days from the date of purchase with their carrier of choice.

    Seller/Merchant make sure to specify shipping costs and related service charges in your listings. What you can only charge is the actual shipping cost, handling cost which there includes also the insurance, value added tax or any government fees.

    Seller/Merchant is required to provide tracking, delivery confirmation or POD (Proof of Delivery)

    If the shipping cost is too high, please make sure to explain and indicate it in your product listing and if there are any dispute or if buyer claims that they didn’t receive the shipment please use on the tracking number as that will serve as your reference to file a claim against this issue.
        </p>
    </section>
</div>

<div class="col-lg-2 col-md-2">
    <h3>Our Policies</h3>
    <ul>
        <li><a href="#company">Our Policy</a></li>
        <li><a href="#membership">Member's Privacy</a></li>
        <li><a href="#shipping">Shipping</a></li>
    </ul>
</div>