<div class="container">
    <div class="text-center" style="padding-bottom: 20px;">
        <h1>Sorry, this page is not available.</h1>
        <p>The link seems to be broken or may have been removed.</p>        
    </div>
    <div class="divider"><hr></div>
    <div class="row-fluid text-center" style="padding: 20px 0px;">
        <div class="advertisement">Advertisement here</div>
    </div>
</div>

<?php //TODO: Capture the error logs for validation ?>