<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        
    <?php
        echo $this->headMeta()
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
            ->appendHttpEquiv('cleartype', 'on')
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendName('HandheldFriendly', 'true');
        
        echo $this->headTitle('Bazaar Corner')
            ->setSeparator(' - ')
            ->setAutoEscape(false);
        
        // SITE WIDE STYLESHEETS
        echo $this->headLink(['rel' => 'favicon', 'href' => $this->basePath('assets/img/site/favicon.ico')])
        ->prependStylesheet($this->basePath('assets/css/layout.css'))
        ->prependStylesheet($this->basePath('assets/bootstrap/css/bootstrap.min.css'))
        ->prependStylesheet($this->basePath('assets/font-awesome/css/font-awesome.min.css'));        
    ?>
        
    </head>
    <body>
        <?= $this->partial('template/partial/header', []); ?>
        <div id="site" class="container">
            <div class="row" id="site-content">
                <?= $this->content; ?>
            </div>
            <div class="row" id="site-footer">
                <?= $this->partial('template/partial/footer', []); ?>
            </div>
            <div class="row footer-border-bottom"></div>
        </div>
        
        <?php 
        // SITE WIDE JAVASCRIPTS
        echo $this->inlineScript()
            ->prependFile($this->basePath('assets/bootstrap/js/tooltip.js'))
            ->prependFile($this->basePath('assets/bootstrap/js/bootstrap.min.js'))
            ->prependFile($this->basePath('assets/jquery/jquery.min.js'));
        ?>
        
    </body>
</html>