<?php echo $this->doctype(); ?>
<!--[if lt IE 7 ]><html class="no-js ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="no-js ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="no-js ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!-->
<html lang="en" class="no-js"><!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <?php echo $this->headMeta()
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
            ->appendHttpEquiv('cleartype', 'on')
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendName('HandheldFriendly', 'true');
        ?>
        <?php echo $this->headTitle('BazaarCorner')
            ->setSeparator(' - ')
            ->setAutoEscape(false);
        ?>
        <?php echo $this->headLink(['rel' => 'shortcut icon', 'href' => $this->basePath() . '/img/favicon.ico'])            
            ->prependStylesheet($this->basePath() . '/css/style.css')
            ->prependStylesheet($this->basePath() . '/assets/font-awesome/css/font-awesome.min.css')
            ->prependStylesheet($this->basePath() . '/assets/bootstrap/css/bootstrap-theme.min.css')
            ->prependStylesheet($this->basePath() . '/assets/bootstrap/css/bootstrap.min.css')
        ?>
    </head>
    <body id="page-top">
        <header>
            <?php echo $this->partial('partial/navigation/header', []); ?>
        </header>        
        <main role="main">
            <?php echo $this->content; ?>
        </main>
        <footer>
            <?php echo $this->partial('template/footer', []); ?>
        </footer>
        <?php echo $this->inlineScript()
            ->prependFile($this->basePath() . '/js/script.js')
            ->prependFile($this->basePath() . '/assets/bootstrap/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.fittext.js')
            ->prependFile('//cdn.jsdelivr.net/fastclick/1.0.3/fastclick.min.js')
            ->prependFile($this->basePath() . '/assets/jquery/jquery.min.js');
        ?>
        
         <?php
            /**
             * USED FOR SITE ANALYTICS. DO NOT EDIT BEYOND THIS LINE.
             */
            if (strtolower($_SERVER['APPLICATION_ENV'])  === 'production') {                
        ?>
            <!-- Google Tag Manager -->
            <noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-T7N3HT"
            height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
            <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
            new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
            j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
            '//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
            })(window,document,'script','dataLayer','GTM-T7N3HT');</script>
            <!-- End Google Tag Manager -->
        <?php
            }
        ?>
    </body>
</html>
