<nav class="navbar navbar-fixed-top" style="background-color: white; box-shadow: 1px 0px 4px silver;">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand img-responsive center-block" href="<?= $this->url('home'); ?>">
                <img src="<?= $this->basePath('assets/img/site/logo.png')?>" style="width: 150px;">
            </a>
        </div>
        <div class="navbar-collapse collapse" id="navbar">
            <div class="nav navbar-left">
                <form class="navbar-form" role="search"
                    method="GET" action="#">
                    <div class="form-group">
                        <div class="input-group">
                            <em style="width: inherit;">
                                <input type="text" class="form-control" 
                                       name="q" 
                                       placeholder="What product you have in mind?">
                            </em>
                            <span class="input-group-btn">
                                <input type="submit" class="btn btn-default">
                            </span>
                        </div>
                    </div>                    
                </form>
            </div>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#"> Market Place </a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                          <!--<i class="fa fa-user"></i>-->
                        Account
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="<?= $this->url('member/login')?>">Sign In</a></li>
                        <li><a href="<?= $this->url('member/registration')?>">Register</a></li>                   
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>